GET localhost:8080/playgrounds

###

POST localhost:8080/playgrounds
Content-Type: application/json

{
  "coordinates": {
    "type": "Point",
    "coordinates": [
      50.0,
      12.3
    ]
  }
}

###

POST localhost:8080/playgrounds
Content-Type: application/json

{
  "lat": 2.0,
  "lon": 2.5
}

###

POST localhost:8080/playgrounds
Content-Type: application/json

{
  "lat": 57.679289,
  "lon": 12.001019
}

###

GET localhost:8080/playgrounds/_search

###
GET localhost:8080/playgrounds/_search/radius
Content-Type: application/json

{
  "lat": 57.68035,
  "lon": 12.004645,
  "distance": 250.0
}
